name:                handlers-in-action
version:             0.1.0.0
github:              "githubuser/handlers-in-action"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/handlers-in-action#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- template-haskell == 2.20.0.0
- haskell-src-exts
- haskell-src-meta
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-export-lists # Should re-enable in the future
- -Wno-incomplete-uni-patterns # Should re-enable in the future
- -Wno-name-shadowing # Should re-enable in the future
- -Wno-unused-matches # Should re-enable in the future
- -Wno-incomplete-patterns # Should re-enable in the future
- -Wno-unused-local-binds # Should re-enable in the future
- -Wno-unused-do-bind # Should re-enable in the future

library:
  source-dirs: src

executables:
  aop-exe:
    main:                AOP
    source-dirs:         app
    other-modules:
    - MRI_code.Advice
    - MRI_code.Effects
    - MRI_code.Interpreters
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action
    - containers

  aopextra-exe:
    main:                AOPExtra
    source-dirs:         app
    other-modules:
    - MRI_code.Advice
    - MRI_code.Effects
    - MRI_code.Interpreters
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action
    - containers

  choice-exe:
    main:                Choice
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action
    - random

  codensitypipes-exe:
    main:                CodensityPipes
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  codensitystate-exe:
    main:                CodensityState
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  delimitedcontinuations-exe:
    main:                DelimitedContinuations
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  exceptions-exe:
    main:                Exceptions
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  freepipes-exe:
    main:                FreePipes
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  freestate-exe:
    main:                FreeState
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  hansei-exe:
    main:                HANSEI
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  handlersentwinedheuristics-exe:
    main:                HandlersEntwinedHeuristics
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  handlersheuristics-exe:
    main:                HandlersHeuristics
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  handlersmonadref-exe:
    main:                HandlersMonadRef
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  iteratees-exe:
    main:                Iteratees
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  lift-exe:
    main:                Lift
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  lifth-exe:
    main:                LiftH
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  list-exe:
    main:                List
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  logic-exe:
    main:                Logic
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  nbe-exe:
    main:                Nbe
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  nbe0-exe:
    main:                Nbe0
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  nim-exe:
    main:                Nim
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  olegiteratees-exe:
    main:                OlegIteratees
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  parse-exe:
    main:                Parse
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  pipes-exe:
    main:                Pipes
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  pipespipes-exe:
    main:                PipesPipes
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  plainstate-exe:
    main:                PlainState
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  primitiverecursion-exe:
    main:                PrimitiveRecursion
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  shallowiteratees-exe:
    main:                ShallowIteratees
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  shallowpipes-exe:
    main:                ShallowPipes
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  shallowstate-exe:
    main:                ShallowState
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  state-exe:
    main:                State
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  stateiteratees-exe:
    main:                StateIteratees
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  updown-exe:
    main:                UpDown
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  wctail-exe:
    main:                WcTail
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

  web-exe:
    main:                Web
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

tests:
  handlers-in-action-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action
