name:                handlers-in-action
version:             0.1.0.0
github:              "githubuser/handlers-in-action"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/handlers-in-action#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- template-haskell == 2.20.0.0
- haskell-src-exts
- haskell-src-meta
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-export-lists # Should re-enable in the future
- -Wno-incomplete-uni-patterns # Should re-enable in the future
- -Wno-name-shadowing # Should re-enable in the future
- -Wno-unused-matches # Should re-enable in the future
- -Wno-incomplete-patterns # Should re-enable in the future
- -Wno-unused-local-binds # Should re-enable in the future
- -Wno-unused-do-bind # Should re-enable in the future

library:
  source-dirs: src

executables:
  handlers-in-action-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action

tests:
  handlers-in-action-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - handlers-in-action
